module.exports = {
  // Room
  MAX_PLAYERS_PER_ROOM: 20,
  ROOM_CLEANUP_INTERVAL: 5 * 60 * 1000,
  PLAYER_TIMEOUT: 30 * 1000,
  MAX_RECONNECT_WAIT: 30 * 1000,

  // Save
  AUTOSAVE_INTERVAL: 60 * 1000,

  // Chat
  MAX_CHAT_LENGTH: 300,
  MAX_CHAT_RATE: 5,
  CHAT_RATE_WINDOW: 10 * 1000,

  // Movement / anti-cheat
  MAX_MOVEMENT_SPEED: 600,
  MAX_TELEPORT_DISTANCE: 800,
  PACKET_RATE_LIMIT: 60,
  PACKET_RATE_WINDOW: 1000,

  // Socket game event rate limiting
  SOCKET_EVENT_RATE_LIMIT: 30,
  SOCKET_EVENT_RATE_WINDOW: 1000,
  MAX_SOCKET_PAYLOAD_BYTES: 8192,

  // JWT
  ACCESS_TOKEN_EXPIRES_IN: '1h',
  REFRESH_TOKEN_EXPIRES_IN: '30d',
  JWT_EXPIRES_IN: '1h',
  BCRYPT_ROUNDS: 12,

  // Password reset
  RESET_TOKEN_EXPIRY_MS: 60 * 60 * 1000,

  // Leaderboard
  LEADERBOARD_SIZE: 100,

  // HTTP Rate limit
  RATE_LIMIT_WINDOW: 15 * 60 * 1000,
  RATE_LIMIT_MAX: 100,
  AUTH_RATE_LIMIT_MAX: 10,
};
